version: '2'
services:
  datastore:
    container_name: myrails-development-datastore
    image: busybox
    volumes:
      - mysql:/var/lib/mysql
      - bundle_install:/usr/local/bundle

  database:
    container_name: myrails-development-database
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes_from:
      - datastore
    ports:
      - 3306:3306

  rails: &rails
    container_name: myrails-development-rails
    image: myrails-development
    build:
      context: .
      dockerfile: Dockerfile.development
    environment: &rails_environment
      RAILS_ENV: development
      DATABASE_URL: mysql2://root@database:3306/sample_database
    depends_on:
      - database
    volumes_from:
      - datastore
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  spring:
    <<: *rails
    container_name: myrails-development-spring
    command: spring server
    environment:
      <<: *rails_environment
      SPRING_SOCKET: /tmp/spring.sock
    ports: []

volumes:
  mysql:
    driver: local
  bundle_install:
    driver: local
