version: '2'
services:
  database:
    container_name: myrails-test-database
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  rails:
    container_name: myrails-test-rails
    image: myrails-test
    build:
      context: ../ # ディレクトリを掘っているため
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
      DATABASE_URL: mysql2://root@database:3306/sample_database
